# Generated by Django 6.0.1 on 2026-05-27 19:36

import reorder_items_widget.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_item_container_anotheritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotheritem',
            name='index',
            field=reorder_items_widget.models.ReorderItemsField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='index',
            field=reorder_items_widget.models.ReorderItemsField(),
        ),
    ]
